Algoritmo "dobrodonumero"
//entrada:ler as 3 notas avaliativas
//processamento: calcular a media das 3 notas
//saida:mostrar a media das 3 notas

Var
   nota1,nota2,nota3,media:real
   


Inicio
   escreva("digite a sua primeira nota ")
   leia(nota1)
   escreva("digite sua segunda nota ")
   leia(nota2)
   escreva("digite sua terceira nota ")
   leia(nota3)
   
   media <- (nota1+nota2+nota3)/3
   
   escreva("A media da sua nota é ", media)


Fimalgoritmo